nome = input("informe seu nome: ")
aluno = input("qual curso voce esta fazendo: ")
print(nome,aluno)
print("nome: {} aluno: {}".format(nome,aluno))
nome = input("informe seu nome completo: ")
print(nome)
print("nome: {}".format(nome))
